# Generated by Django 3.0.8 on 2020-07-06 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email_address', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('room_number', models.CharField(blank=True, max_length=5, null=True)),
                ('subject_taught', models.ManyToManyField(blank=True, to='tms.Subject')),
            ],
        ),
    ]
